### ISSUE TITLE
Not for commercial use?

### ISSUE THREAD

**Issue by halgari** [cognitect-labs/REBL-distro#1]
The license states that:

> You may not use REBL for commercial use.

Could you clarify this? If I write software for a living, or work for a company, does that mean I can't use REBL? Is this project only for use by hobbyists who do not accept compensation for their work?

**Comment by garrett-hopper** [comment]
It seems to me the license was carefully chosen to dissuade widespread use of this specific tool and to instead encourage the community to build tools using the underlying `datafy` and `nav`.
@stuarthalloway, could you speak to this? Is there some other reason for not making this 'free as in speech'?

**Comment by jaidetree** [comment]
https://youtu.be/c52QhiXsmyI?t=1968

That's about the time Stuart says it will be released "Free as in beer".

I interpret it as you can use it while developing something for work but you can't redistribute it and charge for it as work. For instance if you write some kind of paid IDE that you charge for, you cannot include REBL as part of that product.

**Comment by dpsutton** [comment]
This program costs no money: "free as in beer". It is offered to us with in consideration of the agreement posted that says it cannot be used for commercial work. Until someone from cognitect clarifies that I would happily use this for open source and hobby projects but would not install it on a work computer or for a work project.

**Comment by halgari** [comment]
> https://youtu.be/c52QhiXsmyI?t=1968
> 
> That's about the time Stuart says it will be released "Free as in beer".
> 
> I interpret it as you can use it while developing something for work but you can't redistribute it and charge for it as work. For instance if you write some kind of paid IDE that you charge for, you cannot include REBL as part of that product.

That's all conjecture on your part considering "use" and "commercial" are not defined, a side effect of this project using an ad-hoc license. I did some quick googling and the common uses of "not for commercial use" mean that it can't be used for any commercial production. You can't get paid for tutorials that use it, software you built using it, etc. IANAL and all that, but that's why I asked for clarification. The license is so terse, we really don't know what's allowed.

**Comment by jaidetree** [comment]
> > https://youtu.be/c52QhiXsmyI?t=1968
> > That's about the time Stuart says it will be released "Free as in beer".
> > I interpret it as you can use it while developing something for work but you can't redistribute it and charge for it as work. For instance if you write some kind of paid IDE that you charge for, you cannot include REBL as part of that product.
> 
> That's all conjecture on your part considering "use" and "commercial" are not defined, a side effect of this project using an ad-hoc license. I did some quick googling and the common uses of "not for commercial use" mean that it can't be used for any commercial production. You can't get paid for tutorials that use it, software you built using it, etc. IANAL and all that, but that's why I asked for clarification. The license is so terse, we really don't know what's allowed.

You're completely right. It is conjecture. I felt the post above and below mine are also mostly conjecture so I thought: "Why not share some optimistic conjecture?". 

~~From the sound of it Cognitect only has so much time and money at their disposal therefore I'm sure they have better things to do than seeking out projects where devs may have used REBL during the development process.~~

EDIT: Upon reflection my responses in this topic are needlessly reactionary.

Possible options:

1. Since this is early access they could be aiming to charge for the full version for commercial use later or include it as part of another commercial product.
2. The clause is an umbrella to protect themselves against hard-to-define breaches of use (Like reselling it as a frontend UI to an app or repackaging as part of an analytics product).
3. Inspire development of similar apps (Personally, I'm least convinced of this option) 

Cognitect's clarification would be greatly appreciated over relying on any conjecture 😁

**Comment by richhickey** [comment]
Right now, REBL is only available for open source work and hobby projects. We have not yet decided how to make it available for commercial use outside of our Datomic and consulting customers. We'd want to make it available for people making a living in a sustainable way that also lets us make a living, hire UI-savvy Clojurists to work on it and so forth. We're interested in feedback about how much people would be willing to pay for it, per year, for commercial use.

**Comment by orestis** [comment]
Would you consider a free trial period? Integrating a new tool into a company’s workflow needs some experience, and probably a demo impressive enough so that an argument is made to buy it. So during the trial period, it is commercial use, but only for evaluation purposes.

**Comment by orestis** [comment]
Some anchor points for some well-known paid-for tools:

A Cursive License is $99-$199 (perpetual, a year of updates)
Git Tower is $69-$99 (subscription, per year)
IntelliJ is €499 (subscription, per year, gets cheaper every year)
A Clojurists Together individual membership ranges from $60 to $480 (per year)
Slack is $80/year

Others?

**Comment by halgari** [comment]
However, Intelij is free for commercial use, you only pay the €499 if you want the advanced features. Cursive is also nice in that it provides a cheaper option for individuals. $199/yr is hard for a single dev to pay out-of-pocket, but at an enterprise it's so cheap it's almost not worth having a conversation over.

**Comment by jaidetree** [comment]
Thanks for clarifying. Is there a private channel we can provide our pricepoint feedback to?

**Comment by richhickey** [comment]
We've added language to the [EULA](http://rebl.cognitect.com/download.html) to allow Datomic customers to use REBL at work, and have set up a [Patreon membership](https://www.patreon.com/cognitect) so non-customers can do the same!
