### ISSUE TITLE
def as... popup is nasty UX when REBL is full screen

### ISSUE THREAD

**Issue by seancorfield** [cognitect-labs/REBL-distro#24]
My usual way of working on my Mac is to have my editor full-screen and then drag REBL onto that desktop so it is also full-screen taking up a third to a half of the space (with my editor taking up the rest). That way, I can work in the editor, evaluating forms into REBL and seeing results, without the distraction of the O/S chrome/menu bar/dock etc.

Unfortunately, because `def as...` pops up a new window to get the var name, that opens up, expands to a _new_ full-screen desktop, and when you enter the name and you're done, it goes away leaving you on a random desktop other than your editor/REBL pair :( 

It would be much nicer if `def as...` was just a submit button with a text field in front of it that accepted the var name -- so you could just type a name into the field and then press enter or click `def as...` without popping up new windows!

**Comment by richhickey** [comment]
now inline, thanks for the suggestion

**Comment by seancorfield** [comment]
Looking forward to the next version of REBL! Thank you!
