### ISSUE TITLE
Making keyboard controls more platform-native?

### ISSUE THREAD

**Issue by danielcompton** [cognitect-labs/REBL-distro#25]
On macOS, Command (⌘) is usually used as the primary modifier key instead of Control (⌃). Additionally there are system conventions around forwards/backwards that use ⌘[ and ⌘].

The [REBL hotkeys](https://github.com/cognitect-labs/REBL-distro/wiki/Hotkeys) seem to be more general and use Control mostly.

For macOS I would suggest these keys might be more intuitive:

* nav forward: ⌘] or maybe ⌘↓
* nav back: ⌘[ or maybe ⌘↑
* nav root (eval history): unsure
* focus browse: ⌘1
* focus view: ⌘2
* focus browse choice: ⌘3
* focus view choice: ⌘4
* focus code entry: ⌘5 (or whichever order makes the most sense
* eval code: ⌘⏎
* prev expr (in REPL): Unsure, maybe control-UP, or maybe ⌘↑ if that isn't already taken
* next expr (in REPL): control-DOWN
* def as: ⌘D - maybe
* user vars: ⌘U - maybe

I'm happy to look at the Mac HIG and do some more thinking on this if you're interested in taking this idea further.

**Comment by stuarthalloway** [comment]
We plan to expose keybinding configuration, but will likely stick with our most recent keybindings work as basic defaults.
