### ISSUE TITLE
Tuples table viewer sorts numbers alphabetically, not numerically.

### ISSUE THREAD

**Issue by MageMasher** [cognitect-labs/REBL-distro#26]
# Expected
When entering
```
[[1 2 3]
 [2 5 6]
 [11 12 13]
 [21 2 3]]
```
then toggling sorting on column `0`

I expect these numbers to be formatted

```
[[21 2 3]
 [11 12 13]
 [2 5 6]
 [1 2 3]]
```

# Actual

```
[[21 2 3]
 [2 5 6]
 [11 12 13]
 [1 2 3]]
```

# Screenshot
![Screen Shot 2019-05-02 at 11 01 23 AM](https://user-images.githubusercontent.com/1841038/57089708-accfbd80-6cca-11e9-9594-31616dca031d.png)

**Comment by stuarthalloway** [comment]
Thanks for the report! Starting with 0.9.168, sorting will use Clojure's compare if possible.
