### ISSUE TITLE
REBL's REPL is not in a DynamicClassLoader

### ISSUE THREAD

**Issue by seancorfield** [cognitect-labs/REBL-distro#36]
I tried to use the `add-lib` branch of `tools.deps.alpha` with REBL, but got this error:
```
Execution error (IllegalAccessError) at clojure.tools.deps.alpha.repl/add-loader-url (repl.clj:32).
Context classloader is not a DynamicClassLoader
```
Since this is a REPL, it seems like it should provide the same dynamic context that Clojure's regular REPL does.

**Comment by puredanger** [comment]
Related: https://clojure.atlassian.net/browse/CLJ-2540

**Comment by seancorfield** [comment]
Given that this is moving upstream, and I no longer use REBL, I'd be happy for this to be closed (or stay open, up to you), but I'm unsub'ing from lots of old issues at this point.

**Comment by seancorfield** [comment]
Closing due to lack of feedback/interest.
