### ISSUE TITLE
How can you call it as a library?

### ISSUE THREAD

**Issue by bmillare** [cognitect-labs/REBL-distro#5]
I'd like to call cognitect.rebl/ui from an already existing repl (like some long running instance that dynamically loads jars without restarting). So far the only way to get it started is by providing "-m cognitect.rebl" at command line. How do you support this if a clojure repl is already running?

**Comment by jaidetree** [comment]
Created a basic template example repo for how to use REBL with a Leiningen REPL.
https://github.com/jayzawrotny/lein-rebl-example

**Comment by bmillare** [comment]
Got it to work. Here's the answer

> (require
>  '[cemerick.pomegranate :as cp]
>          '[cemerick.pomegranate.aether :as a])
> (-> (Thread/currentThread)
>     (.setContextClassLoader (clojure.lang.RT/baseLoader)))
> (cp/add-dependencies
>  :coordinates
>  '[[org.clojure/core.async "0.4.490"]]
>  :repositories
>  (merge a/maven-central
>         {"clojars" "https://clojars.org/repo"}))
> (require '[clojure.core.async]) ;; I had to include this line once, and then it mysteriously never gave an error again when this was omitted
> (cemerick.pomegranate/add-classpath "/home/bmillare/tmp/REBL-0.9.108/REBL-0.9.108.jar")
> (require 'cognitect.rebl)
> (cognitect.rebl/ui)
