### ISSUE TITLE
Provide JavaFX version using deps

### ISSUE THREAD

**Issue by smahood** [cognitect-labs/REBL-distro#7]
Is it  possible to provide the JavaFX version that REBL needs as part of the deps.edn file? I ran into an issue where my development machines had different versions of the JavaFX API.

**Comment by stuarthalloway** [comment]
What version(s) of Java and JavaFX were the problem combo?

**Comment by smahood** [comment]
With `openjdk version "1.8.0_191"` on Ubuntu, I get a warning `WARNING: Loading FXML document with JavaFX API of version 8.0.141 by JavaFX runtime of version 8.0.60`. After installing and activating the Oracle JDK REBL worked with no problems.  As far as I can recall I installed openjdk from `apt` and never did anything with JavaFX on purpose, so it is likely the default  - though I'm happy to setup a new VM if you have any specific things you want me to check.

I got the same warning when trying to run it with an older version of the Oracle JDK on a mac laptop, but if I had read the readme more carefully I would have seen that it wouldn't work - the JDK and JavaFX were both version 8.0.101.

**Comment by stuarthalloway** [comment]
Thanks Shaun!  I will look at this in the next release.

**Comment by kanwei** [comment]
Also running into this on OpenJDK 11:
```
Execution error (ClassNotFoundException) at jdk.internal.loader.BuiltinClassLoader/loadClass (BuiltinClassLoader.java:583).
javafx.fxml.FXMLLoader
```

In my case, adding javafx-fxml as a dependency hangs on startup forever:
```
:extra-deps  {com.cognitect/rebl      #:local{:root "REBL-0.9.109.jar"}
                                      org.openjfx/javafx-fxml {:mvn/version "11.0.1"}}
```

**Comment by kanwei** [comment]
Alright, this is what's needed for OpenJDK 11 on mac:

1. Download JavaFX manually from https://openjfx.io/openjfx-docs/#install-javafx and unzip the .tgz

2. Add extra deps to :extra-deps
```
:extra-deps
{com.cognitect/rebl          #:local{:root "REBL-0.9.109.jar"}
 org.openjfx/javafx-fxml     #:local{:root "/Users/xxx/javafx-sdk-11.0.1/lib/javafx.fxml.jar"}
 org.openjfx/javafx-controls #:local{:root "/Users/xxx/javafx-sdk-11.0.1/lib/javafx.controls.jar"}
 org.openjfx/javafx-swing    #:local{:root "/Users/xxx/javafx-sdk-11.0.1/lib/javafx.swing.jar"}
 org.openjfx/javafx-base     #:local{:root "/Users/xxx/javafx-sdk-11.0.1/lib/javafx.base.jar"}
 org.openjfx/javafx-web      #:local{:root "/Users/xxx/javafx-sdk-11.0.1/lib/javafx.web.jar"}
 }
```
3. Add extra :jvm-opts
```
:jvm-opts    ["--module-path" "/Users/xxx/javafx-sdk-11.0.1/lib" "--add-modules=javafx.web,javafx.fxml,javafx.swing,javafx.base,javafx.controls"]
```

After all of that, it will now load properly. However, still getting this exception and I can't figure it out, although the data still displays in plain text:

```
2018-12-07 11:38:20,882 [JavaFX Application Thread] ERROR xxx.core - Uncaught exception on JavaFX Application Thread
java.lang.IllegalAccessException: class clojure.lang.Reflector cannot access class com.sun.webkit.dom.NodeListImpl (in module javafx.web) because module javafx.web does not export com.sun.webkit.dom to unnamed module @569c9762
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591)
	at java.base/java.lang.reflect.Method.invoke(Method.java:558)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:167)
	at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:387)
	at cognitect.rebl.fx$get_elements.invokeStatic(fx.clj:271)
	at cognitect.rebl.fx$get_elements.invoke(fx.clj:268)
	at cognitect.rebl.fx$set_webview$reify__11775.changed(fx.clj:294)
```

**Comment by puredanger** [comment]
It would be interesting to try this with `--illegal-access=deny` set. Doing so will cause the Java reflection library to provide feedback that certain reflective calls cannot be made. Clojure (as of 1.10) now uses this feedback to search for an accessible version of the method in the hierarchy to invoke.

**Comment by puredanger** [comment]
I tried to replicate this illegal access error on Java 11 (see details in #10) and was unable to reproduce. Could you provide your full deps.edn? In particular, I'm wondering which version of Clojure you're getting and exactly what starting command line you're using.

**Comment by puredanger** [comment]
Just worked through this with someone experiencing same issue and clearing the classpath cache worked for them (either `rm -rf ./.cpcache` or adding `-Sforce` to the clj command line).

**Comment by puredanger** [comment]
I was able to reproduce this error - https://dev.clojure.org/jira/browse/CLJ-2454 and we will be fixing it for Clojure 1.10.

**Comment by codeasone** [comment]
> With `openjdk version "1.8.0_191"` on Ubuntu, I get a warning `WARNING: Loading FXML document with JavaFX API of version 8.0.141 by JavaFX runtime of version 8.0.60`. 

I'm seeing similar on Linux Mint 19 (bionic-based):

```
Caused by: java.lang.ClassNotFoundException: javafx.fxml.FXMLLoader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.classForName(RT.java:2207)
	at clojure.lang.RT.classForNameNonLoading(RT.java:2220)
	at cognitect.rebl.renderers$loading__6706__auto____11796.invoke(renderers.clj:3)
```
With: 
```
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (Zulu 8.31.0.1-linux64) (build 1.8.0_181-b02)
OpenJDK 64-Bit Server VM (Zulu 8.31.0.1-linux64) (build 25.181-b02, mixed mode)
``` 
And with following in my `deps.edn`: 

```
 :aliases
 {:rebl {:extra-deps {org.clojure/clojure {:mvn/version "1.10.0-RC4"}
                      org.clojure/core.async {:mvn/version "0.4.490"}
                      com.cognitect/rebl
                      {:local/root "/home/mark/.local/bin/REBL-0.9.109/REBL-0.9.109.jar"}}}}
```

**Comment by jonahbenton** [comment]
Data point: was able to piggyback on @kanwei above to get REBL up on openjdk11 on fedora:

0. install openjdk 11 

    sudo dnf install java-11-openjdk

1. download and untar the fx package arbitrarily into $HOME/lib

    https://openjfx.io/openjfx-docs/#install-javafx

2. as per instructions, add PATH_TO_FX to the environment

    export PATH_TO_FX=/home/jbenton/lib/javafx-sdk-11.0.2/lib

3. deps.edn; I needed to add the other jars and modules to resolve various ClassNotFoundException, and arbitrarily put swt ahead of swing in the modules list:

    {:deps {},
     :aliases
     {:rebl
      {:extra-deps
       {
     org.openjfx/javafx-base     #:local{:root "/home/jbenton/lib/javafx-sdk-11.0.2/lib/javafx.base.jar"}
     org.openjfx/javafx-controls #:local{:root "/home/jbenton/lib/javafx-sdk-11.0.2/lib/javafx.controls.jar"}
     org.openjfx/javafx-fxml     #:local{:root "/home/jbenton/lib/javafx-sdk-11.0.2/lib/javafx.fxml.jar"}
     org.openjfx/javafx-graphics #:local{:root "/home/jbenton/lib/javafx-sdk-11.0.2/lib/javafx.graphics.jar"}
     org.openjfx/javafx-media    #:local{:root "/home/jbenton/lib/javafx-sdk-11.0.2/lib/javafx.media.jar"}
     org.openjfx/javafx-swing    #:local{:root "/home/jbenton/lib/javafx-sdk-11.0.2/lib/javafx.swing.jar"}
     org.openjfx/javafx-swt      #:local{:root "/home/jbenton/lib/javafx-sdk-11.0.2/lib/javafx-swt.jar"}
     org.openjfx/javafx-web      #:local{:root "/home/jbenton/lib/javafx-sdk-11.0.2/lib/javafx.web.jar"}
     org.clojure/core.async #:mvn{:version "0.4.490"},
     org.clojure/clojure #:mvn{:version "1.10.0"},
     com.cognitect/rebl #:local{:root "REBL-0.9.109.jar"}
     }
    :jvm-opts    ["--module-path" "/home/jbenton/lib/javafx-sdk-11.0.2/lib" "--add-modules=javafx.web,javafx.fxml,javafx.swt,javafx.swing,javafx.base,javafx.controls,javafx.media,javafx.graphics"]
     }}}
 
4. tell X where to render 

    DISPLAY=":0" clj  -R:rebl -m cognitect.rebl

**Comment by Ramblurr** [comment]
On Fedora with Cursive/Intellij and lein I did thte following:

1. Place the rebl jar file in `resources/` in my projec dir
2. Add to `project.clj` `:resource-paths ["resources/REBL-0.9.109.jar"]`
3. Download openjfx and extract it to ~/vendor (see @jonahbenton's #1 and 2 above)
4. Edit the Cursive REPL run config so that **JVM Args** contains 
    ```--module-path
    /home/myuser/vendor/javafx-sdk-11.0.2/lib
    --add-modules=javafx.web,javafx.fxml,javafx.swt,javafx.swing,javafx.base,javafx.controls,javafx.media,javafx.graphics```
5. Restart repl, and `(rebl/ui)`

**Comment by pmonks** [comment]
Riffing on what @jonahbenton and @kanwei found, a REBL user doesn't have to download JavaFX themselves.  Since being decoupled from the JVM, JavaFX has offered a semi-sane set of Maven artifacts that can be used just like any other dependency.

For example, on Java 11+, one can add the following Maven dependencies to `deps.edn` and avoid having to download JavaFX manually:

```
    org.openjfx/javafx-controls #:mvn{:version "13"},
    org.openjfx/javafx-swing #:mvn{:version "13"},
    org.openjfx/javafx-web #:mvn{:version "13"},
    org.openjfx/javafx-fxml #:mvn{:version "13"},
```

Note: it's possible there are other JavaFX dependencies that are required, though in a quick 5 minute play with REBL this seemed to be the minimal set required to get it working.

**Comment by puredanger** [comment]
@pmonks yes, this has been discussed in other issues (https://github.com/cognitect-labs/REBL-distro/issues/10#issuecomment-451173909) and is even doc'ed on the wiki now (https://github.com/cognitect-labs/REBL-distro/wiki/Java-11-Usage).

**Comment by pmonks** [comment]
Might I suggest fixing the `deps.edn` in the download package then, rather than relying solely on TFM?

If you want to avoid the problem of having to provide multiple downloads (due to the unfortunate history of JavaFX packaging), you could include these dependencies in the `deps.edn` file, commented out in such a way that it's obvious what the user should do next.

FWIW I found my way here via Google from a Clojureverse post, and the wiki is below the fold when one googles "Cognitect REBL".  The links above the fold are:
1. http://rebl.cognitect.com/download.html
2. https://github.com/cognitect-labs/REBL-distro
3. https://www.youtube.com/watch?v=c52QhiXsmyI
4. https://www.youtube.com/watch?v=ZhzMoEz4j1k
5. https://www.youtube.com/watch?v=AahpkP3DZhw

(these last 3 have previews, which take up significant vertical page real estate)

**Comment by puredanger** [comment]
REBL 0.9.226 now contains deps.edn files for Java 8 distributions where JavaFX is included (notably NOT AdoptOpenJDK) and Java 11+ with Open JavaFX 15-ea6. These are our recommended usage versions. See https://github.com/cognitect-labs/REBL-distro#usage for more details.
