### ISSUE TITLE
What host/port to connect to?

### ISSUE THREAD

**Issue by matthewdowney** [cognitect-labs/REBL-distro#9]
If I start REBL via cognitect.rebl/main, where can I point my editor (Cursive) to evaluate forms from the editor in REBL?

**Comment by stuarthalloway** [comment]
Hi Matthew, can you try https://github.com/cognitect-labs/REBL-distro/wiki/REBL-in-IntelliJ-Cursive and see if that works for you?

Thanks!

**Comment by matthewdowney** [comment]
Hey Stuart, works like a charm, thank you!

**Comment by stuarthalloway** [comment]
Glad to hear it!
